### ISSUE TITLE
Please add support for ESP8266 and 10bit

### ISSUE THREAD

**Issue by mkroplewski** [technosf/ESPxRGB#1]
Hey, this library is just what I was looking for, and you are doing amazing job.
However when I tried this on esp8266, it spit out some errors. Is it possible to add support for esp8266 ? Also, 10bit conversion would be awesome, cause esp is using 1024 logic on PWM pins, so 8bit values need to be scaled up, which causes the led strip to be less smooth. I haven't found any library that would convert to 10bit values. Thanks!

**Comment by technosf** [comment]
The ESP8266 is obsolete and uses an older toolchain from Espressif. I would suggest upgrading your hardware.

I'd be interested to know the struct your are storing your 10-bit data, but certainly I had thought of doing a 16-bit version.
